PetFindMeShop.Web/Controllers/ProductController.cs
namespace PetFindMeShop.Web.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using PetFindMeShop.Services.Interfaces;
    using PetFindMeShop.Services.Models;
    using PetFindMeShop.ViewModels.Product;
    using PetFindMeShop.Web.Infrastructure.Extensions;

    using static Common.NotificationMessagesConstants;

    [Authorize]
    public class ProductController : ErrorController
    {
        private readonly IProductService productService;
        private readonly ICategoryService categoryService;
        private readonly IShopManagerService shopManagerService;

        public ProductController(
            IProductService productService,
            ICategoryService categoryService,
            IShopManagerService shopManagerService)
        {
            this.productService = productService;
            this.categoryService = categoryService;
            this.shopManagerService = shopManagerService;
        }

        [HttpGet]
        [AllowAnonymous]
        [Route("/products/all")]
        public async Task<IActionResult> AllProducts([FromQuery] AllProductsQueryModel queryModel)
        {
            AllProductsFilteredAndPagedServiceModel serviceModel = await productService.AllAsync(queryModel);

            queryModel.Products = serviceModel.Products;
            queryModel.TotalProducts = serviceModel.TotalProductsCount;
            queryModel.Categories = await categoryService.AllCategoryNamesAsync();

            return View(queryModel);
        }

        [HttpGet]
        [AllowAnonymous]
        [Route("/products/details/{id?}")]
        public async Task<IActionResult> Details(int id)
        {
            bool isProductExists = await productService.ExistsByIdAsync(id);

            if (!isProductExists)
            {
                return NotFoundError();
            }

            string? userId = User.GetId();

            try
            {
                ProductDetailsViewModel viewModel = await productService.GetDetailsByIdAsync(id, userId!);

                return View(viewModel);
            }
            catch (Exception)
            {
                return GeneralError();
            }
        }

        [HttpGet]
        [Route("/manager/shops/{id}/add-product")]
        public async Task<IActionResult> Create(int id)
        {
            string? userId = User.GetId();
            bool isAdmin = User.IsAdmin();
            bool isShopOwner = await shopManagerService.ManagerAllowedToAccess(id, userId!);

            if (!isShopOwner && !isAdmin)
            {
                return ForbiddenError();
            }

            try
            {
                ProductFormViewModel formModel = new ProductFormViewModel()
                {
                    Categories = await categoryService.AllCategoriesAsync()
                };

                return View(formModel);
            }
            catch (Exception)
            {
                return GeneralError();
            }
        }

        [HttpPost]
        [Route("/manager/shops/{id}/add-product")]
        public async Task<IActionResult> Create(int id, ProductFormViewModel formModel)
        {
            string? userId = User.GetId();
            bool isAdmin = User.IsAdmin();
            bool isShopOwner = await shopManagerService.ManagerAllowedToAccess(id, userId!);

            if (!isShopOwner && !isAdmin)
            {
                return ForbiddenError();
            }

            bool categoryExists = await categoryService.ExistsByIdAsync(formModel.CategoryId);
            if (!categoryExists)
            {
                // Adding model error to ModelState automatically makes ModelState Invalid
                ModelState.AddModelError(nameof(formModel.CategoryId), "Изберете валидна категория");
            }

            if (!ModelState.IsValid)
            {
                formModel.Categories = await categoryService.AllCategoriesAsync();

                return View(formModel);
            }

            try
            {
                await productService.Create(id, formModel);

                TempData[SuccessMessage] = "Успешно създаване!";

                return RedirectToAction("Details", "Shop", new { id });
            }
            catch (Exception)
            {
                return GeneralError();
            }
        }

        [HttpGet]
        [Route("/manager/shops/products/edit/{id}")]
        public async Task<IActionResult> Edit(int id)
        {
            bool isProductExists = await productService.ExistsByIdAsync(id);

            if (!isProductExists)
            {
                return NotFoundError();
            }

            string? userId = User.GetId();
            bool isAdmin = User.IsAdmin();
            int shopId = await productService.GetProductShopIdAsync(id);
            bool isShopOwner = await shopManagerService.ManagerAllowedToAccess(shopId, userId!);

            if (!isShopOwner && !isAdmin)
            {
                return ForbiddenError();
            }

            try
            {
                ProductFormViewModel formModel = await productService.GetProductForEditByIdAsync(id);
                formModel.Categories = await categoryService.AllCategoriesAsync();

                ViewData["id"] = id;

                return View(formModel);
            }
            catch (Exception)
            {
                return GeneralError();
            }
        }

        [HttpPost]
        [Route("/manager/shops/products/edit/{id}")]
        public async Task<IActionResult> Edit(int id, ProductFormViewModel formModel)
        {
            bool isProductExists = await productService.ExistsByIdAsync(id);

            if (!isProductExists)
            {
                return NotFoundError();
            }

            string? userId = User.GetId();
            bool isAdmin = User.IsAdmin();
            int shopId = await productService.GetProductShopIdAsync(id);
            bool isShopOwner = await shopManagerService.ManagerAllowedToAccess(shopId, userId!);

            if (!isShopOwner && !isAdmin)
            {
                return ForbiddenError();
            }

            if (!ModelState.IsValid)
            {
                ViewData["id"] = id;

                return View(formModel);
            }

            try
            {
                await productService.Edit(id, formModel);

                TempData[SuccessMessage] = "Успешно редактиране!";

                return RedirectToAction("Details", "Shop", new { id = shopId });
            }
            catch (Exception)
            {
                return GeneralError();
            }
        }

        [HttpPost]
        public async Task<IActionResult> Archive(int id)
        {
            bool isProductExists = await productService.ExistsByIdAsync(id);

            if (!isProductExists)
            {
                return NotFoundError();
            }

            string? userId = User.GetId();
            bool isAdmin = User.IsAdmin();
            int shopId = await productService.GetProductShopIdAsync(id);
            bool isShopOwner = await shopManagerService.ManagerAllowedToAccess(shopId, userId!);

            if (!isShopOwner && !isAdmin)
            {
                return ForbiddenError();
            }

            bool isProductActivated = await productService.ProductAlreadyArchived(id);

            if (isProductActivated)
            {
                TempData[SuccessMessage] = "Продуктът вече e архивиран!";

                return Redirect(Request.Headers["Referer"].ToString());
            }

            try
            {
                await productService.Archive(id);

                TempData[SuccessMessage] = "Продуктът е архивиране!";

                return Redirect(Request.Headers["Referer"].ToString());
            }
            catch (Exception)
            {
                return GeneralError();
            }
        }

        [HttpPost]
        public async Task<IActionResult> Activate(int id)
        {
            bool isProductExists = await productService.ExistsByIdAsync(id);

            if (!isProductExists)
            {
                return NotFoundError();
            }

            string? userId = User.GetId();
            bool isAdmin = User.IsAdmin();
            int shopId = await productService.GetProductShopIdAsync(id);
            bool isShopOwner = await shopManagerService.ManagerAllowedToAccess(shopId, userId!);

            if (!isShopOwner && !isAdmin)
            {
                return ForbiddenError();
            }

            bool isProductActivated = await productService.ProductAlreadyArchived(id);

            if (!isProductActivated)
            {
                TempData[SuccessMessage] = "Продуктът вече e активен!";

                return Redirect(Request.Headers["Referer"].ToString());
            }

            try
            {
                await productService.Activate(id);

                TempData[SuccessMessage] = "Продуктът е активиран!";

                return Redirect(Request.Headers["Referer"].ToString());
            }
            catch (Exception)
            {
                return GeneralError();
            }
        }

        [HttpPost]
        public async Task<IActionResult> AddToLikedCollection(int id)
        {
            bool isProductExists = await productService.ExistsByIdAsync(id);

            if (!isProductExists)
            {
                TempData[ErrorMessage] = "Продуктът не съществува!";

                return Redirect(Request.Headers["Referer"].ToString());
            }

            string? userId = User.GetId();
            bool isLiked = await productService.ProductAlreadyAddedToCustomerLikedCollection(userId!, id);

            if (isLiked)
            {
                TempData[ErrorMessage] = "Продуктът вече е добавен в любими!";

                return Redirect(Request.Headers["Referer"].ToString());
            }

PetFindMeShop.Web/Controllers/ShoppingCartController.cs
namespace PetFindMeShop.Web.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using PetFindMeShop.Services.Interfaces;
    using PetFindMeShop.ViewModels.Product;
    using PetFindMeShop.Web.Infrastructure.Extensions;
    using PetFindMeShop.Web.Infrastructure.Filters;

    using static Common.NotificationMessagesConstants;

    [Authorize]
    public class ShoppingCartController : ErrorController
    {
        private readonly IShoppingCartService shoppingCartService;
        private readonly IShoppingCartItemService shoppingCartItemService;

        public ShoppingCartController(
            IShoppingCartService shoppingCartService,
            IShoppingCartItemService shoppingCartItemService)
        {
            this.shoppingCartService = shoppingCartService;
            this.shoppingCartItemService = shoppingCartItemService;
        }

        public IActionResult MyShoppingCart()
        {
            return View();
        }

        [HttpPost]
        [ServiceFilter(typeof(ProductExistsValidationFilter))]
        public async Task<IActionResult> AddToCart(int id, ProductBoughtQuantityFormViewModel formModel)
        {
            if (!ModelState.IsValid)
            {
                TempData[ErrorMessage] = "Невалидно количество!";

                return View("~/Views/Product/Details.cshtml", formModel);
            }

            try
            {
                string? userId = User.GetId();
                bool isUserHasCart = await shoppingCartService.ExistsByUserIdAsync(userId!);

                if (!isUserHasCart)
                {
                    await shoppingCartService.CreateUserShoppingCart(userId!);
                }

                string shoppingCartId = await shoppingCartService.GetCartIdByUserIdAsync(userId!);
                bool isItemAddedToCart = await shoppingCartItemService.ProductAddedToCart(id, shoppingCartId!);

                if (!isItemAddedToCart)
                {
                    await shoppingCartItemService.AddProductToCart(id, shoppingCartId, formModel);

                    TempData[SuccessMessage] = "Продуктът е добавен в количката!";

                    return Redirect(Request.Headers["Referer"].ToString());

                }
                else
                {
                    await shoppingCartItemService.UpdateProductInCart(id, shoppingCartId, formModel);

                    TempData[SuccessMessage] = "Продуктът в количката е обновен!";

                    return Redirect(Request.Headers["Referer"].ToString());
                }
            }
            catch (Exception)
            {
                return GeneralError();
            }
        }
    }
}

PetFindMeShop.Web/Views/Product/AllProducts.cshtml
@model AllProductsQueryModel

@{
    ViewBag.Title = "Продукти";
}

<div class="container">
    <h1>Всички продукти</h1>

    <form method="get d-flex justify-content-center">
        <div class="row justify-content-center mt-4 mb-4">
            <div class="form-group d-flex-column col-md-2">
                <div class="form-group">
                    <label asp-for="Category" class="mb-1"></label>
                    <select asp-for="Category" class="form-select form-control">
                        <option value="">Всички</option>
                        @foreach (var category in Model.Categories)
                        {
                            <option value="@category">@category</option>
                        }
                    </select>
                </div>   
            </div>

            <div class="form-group d-flex-column col-md-2">
                <div class="form-group d-flex-column">
                    <label asp-for="ProductsPerPage" class="mb-1"></label>
                    <select asp-for="ProductsPerPage" class="form-select form-control">
                        <option value="3">3</option>
                        <option value="6">6</option>
                        <option value="9">9</option>
                    </select>
                </div>
            </div>

            <div class="form-group d-flex-column col-md-4">
                <label asp-for="SearchString" class="mb-1"></label>
                <input asp-for="SearchString" class="form-control" placeholder="Какво търсиш?">
            </div>

            <div class="form-group d-flex-column col-md-2">
                <div class="form-group">
                    <label asp-for="ProductSorting" class="mb-1"></label>
                    <select asp-for="ProductSorting" class="form-select form-control">
                        <option value="0">Най-нови</option>
                        <option value="1">Най-стари</option>
                        <option value="2">Цена (Възх)</option>
                        <option value="3">Цена (Низх)</option>
                    </select>
                </div>
            </div>

            <div class="d-flex align-items-end col-md-2 mt-4">
                <div class="form-group w-100">
                    <input type="submit" value="Търси" class="btn btn-primary w-100" />
                </div>
            </div>
        </div>
    </form>

    @if (Model.Products.Any())
    {
        <div class="row w-100">
            @foreach (var product in Model.Products)
            {
                <partial name="_ProductAllPartial" model="@product" />
            }
        </div>        
    }
    else
    {
        <h4 class="mt-4 mb-4">Няма намерени продукти!</h4>
    }
    
    @{
        int previousPage = Model.CurrentPage - 1;
        if (previousPage < 1)
        {
            previousPage = 1;
        }

        int maxPage = (int)Math.Ceiling((double)Model.TotalProducts /
        Model.ProductsPerPage);
    }

    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            <li class="page-item @(Model.CurrentPage == 1 ? "disabled" : string.Empty)">
                <a class="page-link"
                   asp-controller="Product"
                   asp-action="AllProducts"
                   asp-route-currentPage="@previousPage"
                   asp-route-ProductsPerPage="@(Model.ProductsPerPage)"
                   asp-route-category="@Model.Category"
                   asp-route-searchTerm="@Model.SearchString"
                   asp-route-sorting="@((int)Model.ProductSorting)">Предишна</a>
            </li>

            @{
                int pages = (int)Math.Ceiling((double)Model.TotalProducts / Model.ProductsPerPage);
            }

            @for (int i = 1; i <= pages; i++)
            {
                @if (i == Model.CurrentPage)
                {
                    <li class="page-item active">
                        <span class="page-link">
                            @i
                            <span class="sr-only"></span>
                        </span>
                    </li>
                } else
                {
                    <li class="page-item">
                        <a class="page-link"
                           asp-controller="Product"
                           asp-action="AllProducts"
                           asp-route-currentPage="@(i)"
                           asp-route-ProductsPerPage="@(Model.ProductsPerPage)"
                           asp-route-category="@Model.Category"
                           asp-route-searchTerm="@Model.SearchString"
                           asp-route-sorting="@((int)Model.ProductSorting)">@i</a>
                        </li>
                }
            }

            @{
                bool shouldNextPageBeDisabled = Model.CurrentPage == maxPage ||
                !Model.Products.Any();
            }

            <li class="page-item @(shouldNextPageBeDisabled ? "disabled" : string.Empty)">
                <a class="page-link"
                   asp-controller="Product"
                   asp-action="AllProducts"
                   asp-route-currentPage="@(Model.CurrentPage + 1)"
                   asp-route-ProductsPerPage="@(Model.ProductsPerPage)"
                   asp-route-category="@Model.Category"
                   asp-route-searchTerm="@Model.SearchString"
                   asp-route-sorting="@((int)Model.ProductSorting)">Следваща</a>
            </li>
        </ul>
    </nav>
</div>

PetFindMeShop.Web/Views/Product/Create.cshtml
@{
    ViewBag.Title = "Добави продукт";
}

<h2 class="text-center">@ViewBag.Title</h2>

@if (!ViewData.ModelState.IsValid && ViewData.ModelState["Error"] != null)
{
    <div class="alert alert-danger" role="alert">
        @ViewData.ModelState["Error"].Errors.First().ErrorMessage
    </div>
}

<partial name="_ProductFormPartial"/>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

PetFindMeShop.Web/Views/Product/Details.cshtml
@model ProductDetailsViewModel

@{
    ViewBag.Title = "Детайли за Продукт" + @Model.Title;
}

<h2 class="text-center">@Model.Title</h2>

<div class="container" style="display:inline">
    <div class="row">
        <div class="col-6 d-flex align-items-center justify-content-center">
            <img src="@Model.ImageName" alt="@ViewBag.Title" class="card-img-top mb-4" style="width: 20rem;">
        </div>
        <div class="card col-6 align-items-center justify-content-center border-0 mb-4">
            <div class="product-info w-90">
                <p><b>Категория: </b>@Model.Category</p>
                <p><b>Предлаган от: </b>@Model.ShopProviderName</p>
                <p><b>Цена: @($"{Model.Price:f2}") лв.</b></p>
                <p class="@(Model.IsAvailable ? "text-success" : "text-danger")"><i>@Model.Status</i></p>
            </div>
            <div class="product-buttons d-flex flex-column flex-column align-items-center justify-content-center w-100">
                @if (!@Model.IsDeleted)
                {
                    <partial name="_ProductBoughtQuantityFormPartial" model="@Model" />
                    @*<form asp-controller="ShoppingCart" asp-action="AddToCart" asp-route-id="@Model.Id" class="boughtQuantityForm" method="post">
                        <div class="d-flex d-flex-row align-items-center align-self-start w-90" style="padding: 0 5%;">
                            <label asp-for="@Model.BoughtQuantityForm.BoughtQuantity" class="mb-1" style="margin-right: 1rem"></label>
                            <div class="wrapper mb-2">
                                <a class="plusminus minus">-</a>
                                <input asp-for="@Model.BoughtQuantityForm.BoughtQuantity" value="@(Model.BoughtQuantityForm.BoughtQuantity != 0 ? Model.BoughtQuantityForm.BoughtQuantity : 1)" class="num" min="1" max="100">
                                <span asp-validation-for="@Model.BoughtQuantityForm.BoughtQuantity" class="small text-danger"></span>
                                <a class="plusminus plus">+</a>
                            </div>
                        </div>
                        <button class="btn btn-primary w-90 mb-2 @(Model.IsAvailable ? "" : "disabled")">Добави в количката</button>
                    </form>*@
                                    
                    @if (!@Model.IsLiked)
                    {
                        @using (Html.BeginForm("AddToLikedCollection", "Product", new { id = @Model.Id }, FormMethod.Post, true,  new { @style = "width: 100%;" }))
                        {
                            @Html.AntiForgeryToken()

                            <div class="flex-column d-flex flex-column align-items-center justify-content-center w-100">
                                <input type="submit" class="btn btn-outline-primary w-90 mb-2" value="Добави в Любими" />
                            </div>
                        }
                    }
                    else
                    {
                        @using (Html.BeginForm("RemoveFromLikedCollection", "Product", new { id = @Model.Id }, FormMethod.Post, true, new { @style = "width: 100%;" }))
                        {
                            @Html.AntiForgeryToken()

                            <div class="flex-column d-flex flex-column align-items-center justify-content-center w-100">
                                <input type="submit" class="btn btn-outline-primary w-90 mb-2" value="Премахни от Любими" />
                            </div>
                        }
                    }
                }
                else
                {
                    <p class="text-danger">Продуктът не е наличен</p>
                }
            </div>
        </div>
        <div class="product-description w-90" style="margin: 0 auto;">
            <h4 class="text-left">Описание</h4>
            <p>@Model.Description</p>
        </div>
    </div>
</div>

@*<script src="~/js/quantityValidation.js"></script>*@

PetFindMeShop.Web/Views/Product/Edit.cshtml
@{
    ViewBag.Title = "Редактиране на продукт";
}

<h2 class="text-center">@ViewBag.Title</h2>

@if (!ViewData.ModelState.IsValid && ViewData.ModelState["Error"] != null)
{
    <div class="alert alert-danger" role="alert">
        @ViewData.ModelState["Error"].Errors.First().ErrorMessage
    </div>
}

<partial name="_ProductFormPartial" />

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}