PetFindMeShop.Web/Areas/Admin/Controllers/CategoryController.cs
namespace PetFindMeShop.Web.Areas.Admin.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Caching.Memory;
    using PetFindMeShop.Services.Interfaces;
    using PetFindMeShop.ViewModels.Category;

    using static PetFindMeShop.Common.GeneralApplicationConstants;
    using static PetFindMeShop.Common.NotificationMessagesConstants;

    public class CategoryController : BaseAdminController
    {
        private readonly ICategoryService categoryService;
        private readonly IMemoryCache memoryCache;

        public CategoryController(ICategoryService categoryService, IMemoryCache memoryCache)
        {
            this.categoryService = categoryService;
            this.memoryCache = memoryCache;
        }

        [ResponseCache(Duration = 30, Location = ResponseCacheLocation.Client, NoStore = false)]
        public async Task<IActionResult> All()
        {
            IEnumerable<CategoryViewModel> categories =
                this.memoryCache.Get<IEnumerable<CategoryViewModel>>(CategoriesCacheKey);

            if (categories == null)
            {
                categories = await this.categoryService.AllCategoriesAsync();

                MemoryCacheEntryOptions cacheOptions = new MemoryCacheEntryOptions()
                    .SetAbsoluteExpiration(TimeSpan
                        .FromMinutes(CategoriesCacheDurationMinutes));

                this.memoryCache.Set(CategoriesCacheKey, categories, cacheOptions);
            }

            return View(categories);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CategoryFormViewModel model)
        {
            bool isCategoryNameExists = await categoryService.ExistsByNameAsync(model.Name);

            if (isCategoryNameExists)
            {
                ModelState.AddModelError(nameof(model.Name), "Категорията вече съществува!");
            }

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                await categoryService.Create(model);

                TempData[SuccessMessage] = "Успешно добавена категория!";

                this.memoryCache.Remove(CategoriesCacheKey);
                return RedirectToAction("All");
            }
            catch (Exception)
            {
                return GeneralError();
            }
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            bool isCategoryExists = await categoryService.ExistsByIdAsync(id);

            if (!isCategoryExists)
            {
                TempData[SuccessMessage] = "Несъществуваща категория!";

                return RedirectToAction("All");
            }

            try
            {
                CategoryFormViewModel formModel = await categoryService.GetCategoryForEditByIdAsync(id);

                ViewData["id"] = id;

                return View(formModel);
            }
            catch (Exception)
            {
                return GeneralError();
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, CategoryFormViewModel model)
        {
            bool isCategoryExists = await categoryService.ExistsByIdAsync(id);

            if (!isCategoryExists)
            {
                TempData[SuccessMessage] = "Несъществуваща категория!";

                return RedirectToAction("All");
            }

            bool isCategoryNameExists = await categoryService.ExistsByOtherNameAsync(id, model.Name);

            if (isCategoryNameExists)
            {
                ModelState.AddModelError(nameof(model.Name), "Категорията вече съществува!");

                ViewData["id"] = id;
            }

            if (!ModelState.IsValid)
            {
                ViewData["id"] = id;

                return View(model);
            }

            try
            {
                await categoryService.Edit(id, model);

                TempData[SuccessMessage] = "Успешно редактиване!";

                this.memoryCache.Remove(CategoriesCacheKey);
                return RedirectToAction("All");
            }
            catch (Exception)
            {
                return GeneralError();
            }
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            bool isCategoryExists = await categoryService.ExistsByIdAsync(id);

            if (!isCategoryExists)
            {
                TempData[SuccessMessage] = "Несъществуваща категория!";

                return RedirectToAction("All");
            }

            try
            {
                await categoryService.Delete(id);

                TempData[SuccessMessage] = "Категорията беше успешно изтрита!";

                this.memoryCache.Remove(CategoriesCacheKey);
                return RedirectToAction("All");
            }
            catch (Exception)
            {
                return GeneralError();
            }
        }

        public IActionResult GeneralError()
        {
            TempData[ErrorMessage] = "Възникна грешка! Моля опитайте отново по-късно.";

            return RedirectToAction("Error400", "Home");
        }
    }
}

PetFindMeShop.Web/Areas/Admin/Controllers/UserController.cs
namespace PetFindMeShop.Web.Areas.Admin.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Caching.Memory;
    using PetFindMeShop.Web.Areas.Admin.Services;
    using PetFindMeShop.Web.Areas.Admin.ViewModels;

    using static PetFindMeShop.Common.GeneralApplicationConstants;

    public class UserController : BaseAdminController
    {
        private readonly IUserService userService;
        private readonly IMemoryCache memoryCache;

        public UserController(IUserService userService, IMemoryCache memoryCache)
        {
            this.userService = userService;
            this.memoryCache = memoryCache;
        }

        [ResponseCache(Duration = 30, Location = ResponseCacheLocation.Client, NoStore = false)]
        public async Task<IActionResult> All()
        {
            IEnumerable<UserViewModel> users =
                this.memoryCache.Get<IEnumerable<UserViewModel>>(UsersCacheKey);

            if (users == null)
            {
                users = await this.userService.AllAsync();

                MemoryCacheEntryOptions cacheOptions = new MemoryCacheEntryOptions()
                    .SetAbsoluteExpiration(TimeSpan
                        .FromMinutes(UsersCacheDurationMinutes));

                this.memoryCache.Set(UsersCacheKey, users, cacheOptions);
            }

            return View(users);
        }
    }
}

PetFindMeShop.Web/Controllers/ProductController.cs
namespace PetFindMeShop.Web.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using PetFindMeShop.Services.Interfaces;
    using PetFindMeShop.Services.Models;
    using PetFindMeShop.ViewModels.Product;
    using PetFindMeShop.Web.Infrastructure.Extensions;

    using static Common.NotificationMessagesConstants;

    [Authorize]
    public class ProductController : ErrorController
    {
        private readonly IProductService productService;
        private readonly ICategoryService categoryService;
        private readonly IShopManagerService shopManagerService;

        public ProductController(
            IProductService productService,
            ICategoryService categoryService,
            IShopManagerService shopManagerService)
        {
            this.productService = productService;
            this.categoryService = categoryService;
            this.shopManagerService = shopManagerService;
        }

        [HttpGet]
        [AllowAnonymous]
        [Route("/products/all")]
        public async Task<IActionResult> AllProducts([FromQuery] AllProductsQueryModel queryModel)
        {
            AllProductsFilteredAndPagedServiceModel serviceModel = await productService.AllAsync(queryModel);

            queryModel.Products = serviceModel.Products;
            queryModel.TotalProducts = serviceModel.TotalProductsCount;
            queryModel.Categories = await categoryService.AllCategoryNamesAsync();

            return View(queryModel);
        }

        [HttpGet]
        [AllowAnonymous]
        [Route("/products/details/{id?}")]
        public async Task<IActionResult> Details(int id)
        {
            bool isProductExists = await productService.ExistsByIdAsync(id);

            if (!isProductExists)
            {
                return NotFoundError();
            }

            string? userId = User.GetId();

            try
            {
                ProductDetailsViewModel viewModel = await productService.GetDetailsByIdAsync(id, userId!);

                return View(viewModel);
            }
            catch (Exception)
            {
                return GeneralError();
            }
        }

        [HttpGet]
        [Route("/manager/shops/{id}/add-product")]
        public async Task<IActionResult> Create(int id)
        {
            string? userId = User.GetId();
            bool isAdmin = User.IsAdmin();
            bool isShopOwner = await shopManagerService.ManagerAllowedToAccess(id, userId!);

            if (!isShopOwner && !isAdmin)
            {
                return ForbiddenError();
            }

            try
            {
                ProductFormViewModel formModel = new ProductFormViewModel()
                {
                    Categories = await categoryService.AllCategoriesAsync()
                };

                return View(formModel);
            }
            catch (Exception)
            {
                return GeneralError();
            }
        }

        [HttpPost]
        [Route("/manager/shops/{id}/add-product")]
        public async Task<IActionResult> Create(int id, ProductFormViewModel formModel)
        {
            string? userId = User.GetId();
            bool isAdmin = User.IsAdmin();
            bool isShopOwner = await shopManagerService.ManagerAllowedToAccess(id, userId!);

            if (!isShopOwner && !isAdmin)
            {
                return ForbiddenError();
            }

            bool categoryExists = await categoryService.ExistsByIdAsync(formModel.CategoryId);
            if (!categoryExists)
            {
                // Adding model error to ModelState automatically makes ModelState Invalid
                ModelState.AddModelError(nameof(formModel.CategoryId), "Изберете валидна категория");
            }

            if (!ModelState.IsValid)
            {
                formModel.Categories = await categoryService.AllCategoriesAsync();

                return View(formModel);
            }

            try
            {
                await productService.Create(id, formModel);

                TempData[SuccessMessage] = "Успешно създаване!";

                return RedirectToAction("Details", "Shop", new { id });
            }
            catch (Exception)
            {
                return GeneralError();
            }
        }

        [HttpGet]
        [Route("/manager/shops/products/edit/{id}")]
        public async Task<IActionResult> Edit(int id)
        {
            bool isProductExists = await productService.ExistsByIdAsync(id);

            if (!isProductExists)
            {
                return NotFoundError();
            }

            string? userId = User.GetId();
            bool isAdmin = User.IsAdmin();
            int shopId = await productService.GetProductShopIdAsync(id);
            bool isShopOwner = await shopManagerService.ManagerAllowedToAccess(shopId, userId!);

            if (!isShopOwner && !isAdmin)
            {
                return ForbiddenError();
            }

            try
            {
                ProductFormViewModel formModel = await productService.GetProductForEditByIdAsync(id);
                formModel.Categories = await categoryService.AllCategoriesAsync();

                ViewData["id"] = id;

                return View(formModel);
            }
            catch (Exception)
            {
                return GeneralError();
            }
        }

        [HttpPost]
        [Route("/manager/shops/products/edit/{id}")]
        public async Task<IActionResult> Edit(int id, ProductFormViewModel formModel)
        {
            bool isProductExists = await productService.ExistsByIdAsync(id);

            if (!isProductExists)
            {
                return NotFoundError();
            }

            string? userId = User.GetId();
            bool isAdmin = User.IsAdmin();
            int shopId = await productService.GetProductShopIdAsync(id);
            bool isShopOwner = await shopManagerService.ManagerAllowedToAccess(shopId, userId!);

            if (!isShopOwner && !isAdmin)
            {
                return ForbiddenError();
            }

            if (!ModelState.IsValid)
            {
                ViewData["id"] = id;

                return View(formModel);
            }

            try
            {
                await productService.Edit(id, formModel);

                TempData[SuccessMessage] = "Успешно редактиране!";

                return RedirectToAction("Details", "Shop", new { id = shopId });
            }
            catch (Exception)
            {
                return GeneralError();
            }
        }

        [HttpPost]
        public async Task<IActionResult> Archive(int id)
        {
            bool isProductExists = await productService.ExistsByIdAsync(id);

            if (!isProductExists)
            {
                return NotFoundError();
            }

            string? userId = User.GetId();
            bool isAdmin = User.IsAdmin();
            int shopId = await productService.GetProductShopIdAsync(id);
            bool isShopOwner = await shopManagerService.ManagerAllowedToAccess(shopId, userId!);

            if (!isShopOwner && !isAdmin)
            {
                return ForbiddenError();
            }

            bool isProductActivated = await productService.ProductAlreadyArchived(id);

            if (isProductActivated)
            {
                TempData[SuccessMessage] = "Продуктът вече e архивиран!";

                return Redirect(Request.Headers["Referer"].ToString());
            }

            try
            {
                await productService.Archive(id);

                TempData[SuccessMessage] = "Продуктът е архивиране!";

                return Redirect(Request.Headers["Referer"].ToString());
            }
            catch (Exception)
            {
                return GeneralError();
            }
        }

        [HttpPost]
        public async Task<IActionResult> Activate(int id)
        {
            bool isProductExists = await productService.ExistsByIdAsync(id);

            if (!isProductExists)
            {
                return NotFoundError();
            }

            string? userId = User.GetId();
            bool isAdmin = User.IsAdmin();
            int shopId = await productService.GetProductShopIdAsync(id);
            bool isShopOwner = await shopManagerService.ManagerAllowedToAccess(shopId, userId!);

            if (!isShopOwner && !isAdmin)
            {
                return ForbiddenError();
            }

            bool isProductActivated = await productService.ProductAlreadyArchived(id);

            if (!isProductActivated)
            {
                TempData[SuccessMessage] = "Продуктът вече e активен!";

                return Redirect(Request.Headers["Referer"].ToString());
            }

            try
            {
                await productService.Activate(id);

                TempData[SuccessMessage] = "Продуктът е активиран!";

                return Redirect(Request.Headers["Referer"].ToString());
            }
            catch (Exception)
            {
                return GeneralError();
            }
        }

        [HttpPost]
        public async Task<IActionResult> AddToLikedCollection(int id)
        {
            bool isProductExists = await productService.ExistsByIdAsync(id);

            if (!isProductExists)
            {
                TempData[ErrorMessage] = "Продуктът не съществува!";

                return Redirect(Request.Headers["Referer"].ToString());
            }

            string? userId = User.GetId();
            bool isLiked = await productService.ProductAlreadyAddedToCustomerLikedCollection(userId!, id);

            if (isLiked)
            {
                TempData[ErrorMessage] = "Продуктът вече е добавен в любими!";

                return Redirect(Request.Headers["Referer"].ToString());
            }

PetFindMeShop.Web/Areas/Admin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PetFindMe Shop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PetFindMeShop.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.3/toastr.min.css" integrity="sha512-6S2HWzVFxruDlZxI3sXOZZ4/eJ8AcxkQH1+JjSe/ONCEqR9L4Ysq5JdT5ipqtzU7WHalNwzwBv+iE51gNHJNqQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- jQuery -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.3/toastr.min.js" integrity="sha512-lbwH47l/tPXJYG9AcFNoJaTMhGvYWhVM9YI43CT+uteTRRaiLCui8snIgyAN8XWgNjNhCqlAUdzZptso6OCoFQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PetFindMe Shop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item dropdown">
                            <div>
                                <a class="btn dropdown-toggle text-black" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">Админ меню</a>
                                <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                    <li>
                                        <a class="dropdown-item nav-link text-dark" asp-area="Admin" asp-controller="Home" asp-action="Index">Админ панел</a>
                                        <a class="dropdown-item nav-link text-dark" asp-area="Admin" asp-controller="Category" asp-action="All">Всички категории</a>
                                        <a class="dropdown-item nav-link text-dark" asp-area="Admin" asp-controller="User" asp-action="All">Всички потребители</a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Product" asp-action="AllProducts">Продукти</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <partial name="_NotificationsPartial" />
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="row d-flex align-items-center justify-content-center text-center border-top footer text-muted">
        <div class="container">
            <p>&copy; PetFindMe Shop All Rights Reserved @DateTime.UtcNow.Year</p>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PetFindMeShop.Web/Areas/Admin/Views/Shared/_CategoryFormPartial.cshtml
@model CategoryFormViewModel


<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form method="post">
            <div class="form-group mb-2">
                <label asp-for="Name" class="mb-1"></label>
                <input asp-for="Name" class="form-control" placeholder="Храна за куче">
                <span asp-validation-for="Name" class="small text-danger"></span>
            </div>

            <div class="text-center">
                @if (ViewData["id"] == null)
                {
                    <input class="btn btn-primary px-4 mt-3" type="submit" value="Добави" />
                }
                else
                {
                    <input class="btn btn-primary px-4 mt-3" type="submit" value="Редактирай" />
                }
            </div>
        </form>
    </div>
</div>

PetFindMeShop.Web/Areas/Admin/Views/Shared/_DeleteCategoryModalPartial.cshtml
 <!-- Modal -->
<div class="modal fade" id="@("deleteCategoryModal-"+@Model.Id)" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="deleteModalLabel">Изтриване на продукт</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body"> 
                Сигурни ли сте, че искате да изтриете категорията <br>
                <b>@Model.Name</b>?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-primary" data-bs-dismiss="modal">Затвори</button>

                @using (Html.BeginForm("Delete", "Category", new { id = @Model.Id }, FormMethod.Post))
                {
                    @Html.AntiForgeryToken()

                    <input type="submit" value="Изтрий" class="btn btn-danger">
                }
            </div>
        </div>
    </div>
</div>